[package]
name = "br_187"
version = "0.1.0"
edition = "2024"
include = ["resources/**", "src/**"]

[dependencies]
framework = { path = "../framework" }
serde = { version = "1.0", features = ["derive", "rc"] }
specta = { version = "2.0.0-rc.20", features = ["derive"] }
