[package]
name = "python_api"
version = "0.1.0"
edition = "2024"
license-file = "./LICENSE"

[lib]
name = "ofire"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py38"] }
openfire = { path = "../.." }

[package.metadata.maturin]
name = "ofire"
bindings = "pyo3"
