
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async open(filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async save(filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async newTab(newTabState: TabState | null, after: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_tab", { newTabState, after }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentTab() : Promise<Result<Tab, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_tab") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTabs() : Promise<Result<Tab[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tabs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCurrentTab(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_tab", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTab(index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tab", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTab(id: string, newTabState: TabState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tab", { id, newTabState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTabFireAndForget(id: string, newTabState: TabState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tab_fire_and_forget", { id, newTabState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateField(id: string, value: string | null) : Promise<Result<null, ParameterError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_field", { id, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationWithSymbols(parameter: ParameterType) : Promise<Result<CalculationComponent[][], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_with_symbols", { parameter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationWithNumbers(parameter: ParameterType) : Promise<Result<CalculationComponent[][], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_with_numbers", { parameter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationInputs(stepId: number) : Promise<Result<ParameterType[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_inputs", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationInputsSymbols(stepId: number) : Promise<Result<ParameterType[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_inputs_symbols", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCurrentTabMethod(methodType: MethodType) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_tab_method", { methodType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async calculateForm() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_form") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async allImplementations() : Promise<Result<DocumentImplementations[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("all_implementations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async friendlyReference(doc: Document) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("friendly_reference", { doc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async harvardReference(doc: Document) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("harvard_reference", { doc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async documentTitle(doc: Document) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("document_title", { doc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aboutDocument(doc: Document) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("about_document", { doc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aboutMethod(doc: Document) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("about_method", { doc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async methodLimitations(doc: Document) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("method_limitations", { doc }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAgreedToLatestLicense() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_agreed_to_latest_license") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agreeToLicense() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agree_to_license") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openfireVersion() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("openfire_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutoUpdate(activated: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_auto_update", { activated }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAutoUpdate() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_auto_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUpdateSkipped(version: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_update_skipped", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setUpdateSkipped(version: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_update_skipped", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
validationErrorEvent: ValidationErrorEvent
}>({
validationErrorEvent: "validation-error-event"
})

/** user-defined constants **/



/** user-defined types **/

export type BR187Chapter = { One: Chapter1Equation } | "AppendixA"
export type Calculation = { steps: Step[]; stale: boolean }
export type CalculationComponent = { Equation: string } | { EquationWithResult: string } | { Text: string }
export type Chapter10Method = "BurningRegime"
export type Chapter14Method = "HeatReleaseFromTempAndPosition"
export type Chapter1Equation = "One"
export type Comparison = { GreaterThanOrEqual: ParameterType } | { LessThanOrEqual: ParameterType }
export type DisplayOptions = { DecimalPlaces: number }
export type Document = { BR187: BR187Chapter | null } | { PD7974: Part | null } | { SFPEHandbook: SFPEHandbookChapter | null } | { IntroductionToFireDynamics: IntroductionToFireDynamicsChapter | null }
export type DocumentImplementations = { document: string; implementations: Implementation[] }
export type Field = { id: string; name: string; value: string | null; touched: boolean; parameter: ParameterType }
export type FieldType = { Individual: Field } | { Table: Field[][] }
export type Form = { steps: FormStep[] }
export type FormStep = { name: string; description: string; fields: FieldType[]; introduction: IntroComponent[][] }
export type Icon = "FireIcon"
export type Implementation = { name: string; tags: string[]; description: string; reference: Reference; search_reference: string; method_type: MethodType; icon: Icon; colors: string }
export type IntroComponent = { Title: string } | { Text: string } | { Equation: CalculationComponent }
export type IntroductionToFireDynamicsChapter = { Ten: Chapter10Method }
export type Method = { name: string; description: string | null; reference: Reference; method_type: MethodType; parameters: { [key in string]: ParameterType }; quick_calc_compatible: boolean; calc_sheet: Calculation; form: Form }
export type MethodType = "PD7974Part1Section8MaximumEnclosureTemperature" | "PD7974Part1Section8HRRAtFlashover" | "BR187Chapter1Equation1" | "SFPEAlpertHeatReleaseFromTemperatureAndPosition" | "IntroductionToFireDynamcicsChapter10BurningRegime"
export type NoCalc = { id: string }
export type Parameter<T> = { id: string; name: string; value: T | null; display_options: DisplayOptions[]; units: string | null; validations: Validation[] }
export type ParameterError = { ValidationError: { id: string; message: string } }
export type ParameterType = { String: Parameter<string> } | { Float: Parameter<number> } | { Bool: Parameter<boolean> } | { Object: { [key in string]: ParameterType } }
export type Part = { One: Section | null }
export type Reference = Document
export type SFPEHandbookChapter = { Fourteen: Chapter14Method }
export type Section = { Eight: Section8Method }
export type Section8Method = "HRRAtFlashover" | "MaximumEnclosureTemperature"
export type Step = { name: string; parameters: ParameterType[] }
export type Tab = { id: string; state: TabState; saved: boolean; current: boolean; filename: string | null; title: string | null }
export type TabState = ({ type: "Index" } & NoCalc) | ({ type: "Method" } & Method)
export type Validation = "Required" | { MinLength: number } | { MaxLength: number } | { Range: [number, number] } | { MinExclusive: number } | { Min: number } | { Max: number } | { Relation: Comparison }
export type ValidationErrorEvent = { field_id: string; error: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
