
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async open(filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async save(filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async newTab(newTabState: TabState | null, after: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_tab", { newTabState, after }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentTab() : Promise<Result<Tab, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_tab") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTabs() : Promise<Result<Tab[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tabs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCurrentTab(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_tab", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTab(index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tab", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTab(id: string, newTabState: TabState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tab", { id, newTabState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTabFireAndForget(id: string, newTabState: TabState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tab_fire_and_forget", { id, newTabState }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateField(id: string, value: string | null) : Promise<Result<null, ParameterError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_field", { id, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationWithSymbols(parameter: Parameter) : Promise<Result<CalculationComponent[][], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_with_symbols", { parameter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationWithNumbers(parameter: Parameter) : Promise<Result<CalculationComponent[][], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_with_numbers", { parameter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationInputs(stepId: number) : Promise<Result<Parameter[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_inputs", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEquationInputsSymbols(stepId: number) : Promise<Result<Parameter[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_equation_inputs_symbols", { stepId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCurrentTabMethod(methodType: MethodType) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_tab_method", { methodType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async calculateForm() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_form") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async newMethodBuilder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_method_builder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async methodBuilderDeleteMetadata(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("method_builder_delete_metadata", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async methodBuilderAddMetadata() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("method_builder_add_metadata") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async methodBuilderUpdateMetadataRequired(id: string, required: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("method_builder_update_metadata_required", { id, required }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async methodBuilderUpdateMetadataName(id: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("method_builder_update_metadata_name", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
validationErrorEvent: ValidationErrorEvent
}>({
validationErrorEvent: "validation-error-event"
})

/** user-defined constants **/



/** user-defined types **/

export type Calculation = { steps: Step[]; stale: boolean }
export type CalculationComponent = { Equation: string } | { EquationWithResult: string } | { Text: string }
export type Comparison = { GreaterThanOrEqual: Parameter } | { LessThanOrEqual: Parameter }
export type Field = { id: string; name: string; value: string | null; touched: boolean; parameter: Parameter }
export type Form = { steps: FormStep[] }
export type FormStep = { name: string; description: string; fields: Field[] }
export type Metadata = { name: string; required: boolean; value: string | null }
export type MetadataBuilder = { id: string; name: string; required: boolean }
export type Method = { name: string; metadata: Metadata[]; description: string | null; reference: string[]; method_type: MethodType; parameters: { [key in string]: Parameter }; quick_calc_compatible: boolean; calc_sheet: Calculation; form: Form }
export type MethodBuilder = { name: string; metadata: MetadataBuilder[]; description: string | null; reference: string[]; parameters: { [key in string]: Parameter }; quick_calc_compatible: boolean; calc_sheet: Calculation | null; form: Form; method_type: MethodType | null }
export type MethodType = "PD7974Part2Section7Equation1" | "BR187Chapter1Equation1" | "SFPEAlpertHeatReleaseFromTemperatureAndPosition"
export type NoCalc = { id: string }
export type Parameter = { id: string; name: string; parameter_type: ParameterType; value: ParameterValue | null; units: string | null; validations: Validation[] }
export type ParameterError = { ValidationError: { id: string; message: string } }
export type ParameterType = "String" | "Float" | "Bool"
export type ParameterValue = string | number | boolean
export type Step = { name: string; parameters: Parameter[] }
export type Tab = { id: string; state: TabState; saved: boolean; current: boolean; filename: string | null; title: string | null }
export type TabState = ({ type: "Index" } & NoCalc) | ({ type: "Method" } & Method) | ({ type: "MethodBuilder" } & MethodBuilder)
export type Validation = "Required" | { MinLength: number } | { MaxLength: number } | { Range: [number, number] } | { MinExclusive: number } | { Min: number } | { Max: number } | { Relation: Comparison }
export type ValidationErrorEvent = { field_id: string; error: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
