name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    environment: Release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # for Arm based macs (M1 and above).
          #   target: "aarch64-apple-darwin"
          #   s3-directory: "aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            target: "x86_64-apple-darwin"
            s3-directory: "x86_64-apple-darwin"
          # - platform: "ubuntu-22.04"
          #   target: "x86_64-unknown-linux-gnu"
          #   s3-directory: "ubuntu"
          # - platform: "windows-latest"
          #   target: "x86_64-pc-windows-msvc"
          #   s3-directory: "windows"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.target }}

      - name: Build
        id: build
        # create the release and set the output folder for the next step
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p dist
          cp target/${{ matrix.target }}/release/openfire tmp/
          echo appVersion=0.0.1

      - name: import signing certificate
        if: matrix.platform == 'macos-latest'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: sign executable
        if: matrix.platform == 'macos-latest'
        run: |
          /usr/bin/codesign --force -s ${{ secrets.APPLE_SIGNING_IDENTITY }} -o runtime ./tmp/openfire -v
          zip ../dist/openfire_v${{ steps.build.outputs.appVersion }}_v${{ matrix.target }}.zip ./tmp/openfire

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: "OpenFire v${{ steps.build.outputs.appVersion }}"
          body: "See the assets to download this version and install."
          draft: true
          prerelease: false
